// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqjjhtgcngckkewbvdei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxampodGdjbmdja2tld2J2ZGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MzI3MzQsImV4cCI6MjA1OTMwODczNH0.MO9oOtX8jR-Vk191x5Y2VOThDrI-rYBDK4XVA0Iwb5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);