# NOTE: This file has validation issues in some IDEs.
# For a version without validation issues, see market_data_api.openapi.json
#
# This is a simplified version of the OpenAPI specification for the Market Data API.
# The full specification is available in market_data_api.openapi.json
#
# API Endpoints:
# - GET /symbols - List all supported trading symbols
# - GET /ticker - Get latest ticker price for a symbol
# - GET /orderbook - Get current order book snapshot
# - GET /trades - Get recent trades
# - GET /klines - Get historical candlestick data
#
# Authentication:
# - API Key in header: x-api-key
#
# Common Parameters:
# - symbol: Trading pair symbol (e.g., BTCUSDT)
# - limit: Number of results to return
# - interval: Candlestick interval (e.g., 1m, 5m, 1h)
# - startTime: Start timestamp in milliseconds
# - endTime: End timestamp in milliseconds
