name: Deploy Simple GitHub Pages

on:
  workflow_dispatch:  # Allow manual triggering only

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Simple Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Create simple GitHub Pages deployment
        run: npm run deploy:gh-pages-simple

      # Verify the build output
      - name: Verify build output
        run: |
          echo "Checking for index.html:"
          cat ./dist/index.html
          echo "Checking for test.html:"
          cat ./dist/test.html
          echo "Checking for placeholder.svg:"
          ls -la ./dist/placeholder.svg

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
